import React from "react";
import PageWallpaper from "../components/PageWallpaper/PageWallpaper";
import FromCompnent from "../components/FromComponent/FromCompnent";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Navbar/Navbar";
import Head from "next/head";
import HeroSection from "../components/Navbar/Herosection";

//import 'tw-elements';
export default function Home() {
  return (
   <>
			<Head>
				<title>Navigation using nextjs and tailwindcss</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
			</Head>
			<Navbar />
			 <HeroSection /> 
		
    <React.Fragment>

      
      {/* <PageWallpaper /> */}
      <FromCompnent />
      <Footer />
      {/* <PageWallpaper /> */}
    </React.Fragment>
    </>
  )
}